#!/usr/bin/env python3
"""Generate Caddy snippets for anchorage-managed services.

Scans /var/lib/anchorage/*/docker-compose.yml for services with the labels:
  caddy.host: <subdomain>
  caddy.port: <host-port>

Writes site blocks to /etc/caddy/anchorage/services.caddy, which is pulled
in by the main Caddyfile via:  import /etc/caddy/anchorage/*

Reads DOMAIN_SUFFIX from the environment (set via EnvironmentFile in the
systemd unit, sourced from /var/lib/anchorage/env.shared).
"""

import logging
import os
import sys
from pathlib import Path

import yaml

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
log = logging.getLogger(__name__)

BASE_DIR = Path("/var/lib/anchorage")
ANCHORAGE_CADDY_DIR = Path("/etc/caddy/anchorage")
SERVICES_CADDY = ANCHORAGE_CADDY_DIR / "services.caddy"


def get_domain_suffix() -> str:
    suffix = os.environ.get("DOMAIN_SUFFIX", "").strip()
    if not suffix:
        log.error("DOMAIN_SUFFIX is not set in /etc/anchorage/anchorage.conf")
        sys.exit(1)
    return suffix


def find_caddy_services(base_dir: Path) -> list[dict[str, str]]:
    services: list[dict[str, str]] = []
    for compose_file in sorted(base_dir.glob("*/docker-compose.yml")):
        try:
            data = yaml.safe_load(compose_file.read_text()) or {}
        except yaml.YAMLError as exc:
            log.warning("Skipping %s: %s", compose_file, exc)
            continue

        for svc_name, svc_cfg in (data.get("services") or {}).items():
            labels = svc_cfg.get("labels") or {}
            if isinstance(labels, list):
                # docker-compose allows "KEY=VALUE" list syntax
                labels = dict(item.split("=", 1) for item in labels if "=" in item)

            host = str(labels.get("caddy.host", "")).strip()
            port = str(labels.get("caddy.port", "")).strip()
            if host and port:
                services.append({"name": svc_name, "host": host, "port": port})

    return services


def render_services(services: list[dict[str, str]], suffix: str) -> str:
    lines: list[str] = [
        "# Auto-generated by anchorage-gen-caddyfile -- do not edit manually",
    ]
    for svc in services:
        fqdn = f"{svc['host']}.{suffix}"
        lines += [
            "",
            f"{fqdn} {{",
            f"    reverse_proxy 127.0.0.1:{svc['port']} {{",
            "        header_up Host {host}",
            "        header_up X-Real-IP {remote}",
            "    }",
            "}",
        ]
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    suffix = get_domain_suffix()
    services = find_caddy_services(BASE_DIR)
    log.info("Found %d service(s) with Caddy labels", len(services))

    ANCHORAGE_CADDY_DIR.mkdir(parents=True, exist_ok=True)
    content = render_services(services, suffix)
    SERVICES_CADDY.write_text(content)
    log.info("Wrote %s", SERVICES_CADDY)

    for svc in services:
        log.info("  %s.%s -> 127.0.0.1:%s", svc["host"], suffix, svc["port"])


if __name__ == "__main__":
    main()
